#!/bin/bash
if [ $# -lt 1 ];then
   echo "Image prefix required"
   exit 1
fi
docker-compose -p $1 -f docker-compose.yml -f production.yml down -v --remove-orphans
docker-compose -p $1 -f docker-compose.yml -f production.yml up -d --build --force-recreate
