#!/bin/bash
docker-compose -f docker-compose.yml -f production-base.yml -f production-enyo.yml down -v --remove-orphans
docker-compose -f docker-compose.yml -f production-base.yml -f production-enyo.yml up -d
