version: '3'
services:
    backend:
        ports:
            - '8000:80'
        volumes:
            - ./backend/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app:/var/www/html:ro
    app:
        user: ${UID}:${GID}
        volumes:
            - ./app:/var/www/html:rw
