version: '3'
services:
    api:
        volumes:
            - api:/var/www/html:rw
    backend:
        volumes:
            - api:/var/www/html:ro
    frontend:
        build: ./frontend
        ports:
            - 80:80
        depends_on:
            - backend
volumes:
    api:
