version: '3'
services:
    app:
        volumes:
            - app:/var/www/html:rw
    backend:
        volumes:
            - app:/var/www/html:ro
    frontend:
        build: ./frontend
        ports:
            - 80:80
        depends_on:
            - backend
volumes:
    app:
