version: '3'
services:
    frontend:
        restart: always
        build: ./frontend
        depends_on:
            - backend
    backend:
        restart: always
        volumes:
            - app:/var/www/html:ro
    app:
        restart: always
        volumes:
            - app:/var/www/html:rw
    redis:
        restart: always
volumes:
    app:
