version: '3'
services:
    reverse-proxy:
        restart: always
        image: traefik:v2.1
        command: --providers.docker
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    frontend:
        labels:
            - traefik.http.routers.vinland.rule=(Host(``))
