#!/bin/bash
if [ $# -ne 1 ]; then
  echo 1>&2 "Usage: $0 name"
  exit 3
fi

docker-machine status $1 > /dev/null 2>&1

if [ $? -ne 0 ]; then
    echo 1>&2 "machine $1 does not exist"
    exit 3
fi

eval $(docker-machine env $1)
docker-compose -f docker-compose.yml -f production.yml down -v --remove-orphans
docker-compose -f docker-compose.yml -f production.yml up -d --build --force-recreate
eval $(docker-machine env --unset)
