version: '3'
services:
    frontend:
        build: ./frontend
        networks:
            - default
            - proxy
        labels:
            - traefik.http.routers.vinland.rule=Host(`${APP_HOST}`)
        depends_on:
            - backend
    backend:
        volumes:
            - app:/var/www/html:ro
    app:
        volumes:
            - app:/var/www/html:rw
volumes:
    app:
networks:
    proxy:
        external: true
