version: '3'
services:
    frontend:
        networks:
            - default
            - proxy
        labels:
            - traefik.http.routers.vinland.rule=(Host(`${APP_HOST_PRIMARY}`) || Host(`${APP_HOST_SECONDARY}`))
networks:
    proxy:
        external: true
