#!/bin/bash

BASEDIR=$(dirname "$0")

carton exec $BASEDIR/bin/import/proteins
carton exec $BASEDIR/bin/import/proteins_xrefs
carton exec $BASEDIR/bin/import/sequences
carton exec $BASEDIR/bin/import/interactions
carton exec $BASEDIR/bin/import/edges
carton exec $BASEDIR/bin/import/publications
carton exec $BASEDIR/bin/import/methods
carton exec $BASEDIR/bin/import/descriptions
carton exec $BASEDIR/bin/import/mappings
